### ISSUE TITLE
Проблема с кодировкой интерфейса

### ISSUE THREAD

**Issue by RyabykinIlya** [OLDodin/Universe#1]
Так выглядит интерфейс:
![Allods_220429_212857](https://user-images.githubusercontent.com/28308859/166003964-8349653b-c41f-4849-a3de-a85e4b6b7fb2.jpg)

Win11 English

AoUMeter, например, работает норм, там интерфейс отображается на английском.

**Comment by OLDodin** [comment]
По тестирую с дефолтовым английским, а пока можно так починить -

Нужно поменять системную локаль:

    до win10: правой кнопкой на языке внизу справа - настройки языка - дополнительно - самое нижнее - язык программ, не поддерживающих юникод - меняем на русский и ребутаемся.
    win10: левой кнопкой на языке внизу справа - настройки языка - административные языковые параметры - язык программ, не поддерживающих юникод - меняем на русский и ребутаемся.

**Comment by RyabykinIlya** [comment]
@OLDodin работает, спасибо!
