### ISSUE TITLE
mods.tx лог спам

### ISSUE THREAD

**Issue by getSicko** [OLDodin/Universe#4]
Привет, я получил это в спаме на mods.txt начиная с Версия 2.7.1

Error while running the chunk
  /Mods/Addons/Universe/Scripts/GUIController.lua:1286: bad argument #1 to 'ipairs' (table expected, got nil)
  func: ?, ?, line: -1, defined: C, line: -1, [C]
    func: ipairs, global, line: -1, defined: C, line: -1, [C]
      func: FindInListTarget, upvalue, line: 1286, defined: Lua, line: 1285, /Mods/Addons/Universe/Scripts/GUIController.lua
        func: FindTarget, upvalue, line: 1295, defined: Lua, line: 1294, /Mods/Addons/Universe/Scripts/GUIController.lua
          func: ?, ?, line: 1806, defined: Lua, line: 1799, /Mods/Addons/Universe/Scripts/GUIController.lua

Начато после того, как вы изменили эту function

`local function FindInListTarget(anObjID, anObjArr)
	for _, info in ipairs(anObjArr) do
		if info.objID == anObjID then
			return true
		end
	end
	return false
end`

раньше было
`local function FindInListTarget(anObjID, anObjArr)
	for i=1, GetTableSize(anObjArr) do
		if anObjArr[i].objID == anObjID then
			return true
		end
	end
	return false
end`

**Comment by OLDodin** [comment]
Исправил в 2.7.8
