### ISSUE TITLE
Несколько идей

### ISSUE THREAD

**Issue by getSicko** [OLDodin/Universe#5]
Привет, спасибо за работу над этим дополнением, это потрясающе! У меня есть предложения, которые было бы неплохо добавить в будущем, если можно : 
Сделайте возможным добавлять бафов над головой только на свой аватар; 
Процент прозрачности бафф; 
Сделайте возможным щелкать правой кнопкой мыши по бафф, чтобы снять его.

**Comment by OLDodin** [comment]
Про снятие правым кликом - учитывая что для поворота камеры и бега можно нажимать правую кнопку где-то на экране, это будет чревато. Да и не так много баффов которые можно снимать, проще их в стандартном интерфейсе снять, чем в 3д над головой и тп.

**Comment by OLDodin** [comment]
Прозрачность добавлена в версии 3.0 Снятие баффов через ненужным.
