### ISSUE TITLE
После смены профиля новая версия аддона сломалась и не отвечает

### ISSUE THREAD

**Issue by Dumgard** [OLDodin/Universe#6]
Log:
Error while running the chunk
  /Mods/Addons/Universe/Scripts/Forms/ColorSettingsForm.lua:0: attempt to index a nil value
  func: __index, metamethod, line: -1, defined: C, line: -1, [C]
    func: CreateSimpleColorSettingsForm, global, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/Forms/ColorSettingsForm.lua
      func: LoadRaidFormSettings, global, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/Forms/RaidSettings.lua
        func: LoadForms, global, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/GUIController.lua
          func: GUIControllerInit, global, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/GUIController.lua
            func: ?, ?, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/mainscript.lua
              func: ?, ?, line: 0, defined: Lua, line: 0, /Mods/Addons/Universe/Scripts/mainscript.lua
Can't execute script: Mods/Addons/Universe/Scripts/mainscript.lua for addon: Mods/Addons/Universe/AddonDesc.(UIAddon).xdb

После фикса (версия 3.0.2) сменил профиль, аддон сломался и больше не реагирует на перезагрузку\нажатие кнопки, выглядит так:
![изображение](https://github.com/OLDodin/Universe/assets/79639529/8c3244f2-678f-41ee-abdf-52a556d56f15)

Загрузка новой версии (3.0.3) не полечила проблему :(

**Comment by OLDodin** [comment]
Можете из файл AO\data\Mods\Configs\Universe\user.cfg свой скинуть

**Comment by Dumgard** [comment]
[user.cfg.txt](https://github.com/OLDodin/Universe/files/15118781/user.cfg.txt)

**Comment by OLDodin** [comment]
импорт профиля делали?

**Comment by Dumgard** [comment]
Нажал "загрузить" на вкладке профилей. Оба профиля создавал внутри игры (пвп\пве). Стоял один профиль (пве) - загрузил второй (пвп), UI  сломался

**Comment by Dumgard** [comment]
Большое спасибо!! <3

**Comment by Dumgard** [comment]
Проверил, теперь всё работает, ещё раз спасибо Вам за Вашу работу! :)
