### ISSUE TITLE
чтобы увидеть дебаффы на нас, которые можно снять

### ISSUE THREAD

**Issue by nico80286** [OLDodin/Universe#7]
Здравствуйте,
Спасибо за этот замечательный аддон.
Было бы возможно добавить возможность видеть снимаемые баффы, которые накладываются на нас? Эта функция, кажется, существует только для врагов.

**Comment by OLDodin** [comment]
Для пати/рейда в настройках есть "счищаемые баффы(-) на союзниках" и подсветка таких игроков. 
В рейде/пати показывает счищаемые дебаффы, а в таргетере положительные счищаемые на  врагах. По моему всё логично и  всё это уже есть

**Comment by OLDodin** [comment]
Use "auto detect debuffs on friends" checkbox (in version 3.0+ renamed to "Dispelling buffs(–) on friends:")

"auto detect debuffs on friends" = "Friends (target or avatar) - negative removable effects"
"Dispelling buffs on enemy" = "Enemy - positive removable effects"

**Comment by nico80286** [comment]
Woah it works. I'm sorry for the lost time. I was really convinced that I had tested this box correctly, and several times... but actually it works very well.
I'm not used to being so wrong, I double-check before I speak. I must have missed something in my previous tests.
Thank you for your quick replies🙂
